"""
Contains global constants for the application.
"""

STYLE = (
    "QMainWindow {"
    "    background: #f7f8fa;"
    "}"
    "QWidget#stackedRight {"
    "    border: 1px solid #e0e0e0;"
    "    background: #ffffff;"
    "}"
    "QPushButton {"
    "    background: transparent;"
    "    border: none;"
    "    padding: 10px 18px;"
    "    font-size: 15px;"
    "    color: #333;"
    "    border-radius: 6px;"
    "}"
    "QPushButton:hover {"
    "    background: #e3e8ee;"
    "}"
    "QPushButton:pressed {"
    "    background: #cfd8dc;"
    "}"
    "QPushButton[styleSheet*=\"font-weight: bold;\"] {"
    "    color: #1976d2;"
    "    background: #e3e8ee;"
    "}"
)